// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ExamService from "./examservice.js";
export {
    ExamService
};

export {
    AccuracyFilters,
    AnswerItem,
    FileDialogResult,
    OCRConfig,
    ScreenshotArea,
    SearchResult
} from "./models.js";
